### ISSUE TITLE
Recommend Library Telegram Bot SDK

### ISSUE THREAD

**Issue by VictoRD11** [Tegos/travian-bot-laravel#1]
Hello 👋, I recommend a library for writing bots for Telegram Bot SDK ([irazasyed/telegram-bot-sdk](https://github.com/irazasyed/telegram-bot-sdk))
One of the few awesome libraries ✨
There were gaps in the documentation on the website, but the code was well-documented)
But now I see that they have updated the documentation on the site

**Comment by Tegos** [comment]
Hello, mate. Nice to see you. Thanks for your issue.
But I'm not pretty sure, that sdk is needed in this project.
Could you provide some use cases of usage this library?

**Comment by VictoRD11** [comment]
OMG, I'm so stupid, I thought you wanted to make a telegram bot 🤣

**Comment by Tegos** [comment]
No, it is a personal browser-based bot for game Travian 😅

**Comment by VictoRD11** [comment]
https://github.com/Tegos/travian-bot-laravel/blob/37e74c6a137dda7d3cb61c445114b97872a4ca44/app/Travian/Api/Api.php#L19
Is this a rudiment of integration with 1C?)

**Comment by Tegos** [comment]
> https://github.com/Tegos/travian-bot-laravel/blob/37e74c6a137dda7d3cb61c445114b97872a4ca44/app/Travian/Api/Api.php#L19
> 
> 
> Is this a rudiment of integration with 1C?)

![image](https://user-images.githubusercontent.com/7047662/234605335-874897ae-5bc8-4507-b381-2c9c947b8c29.png)
